Add sphere math functions
dimomatt/regional_mesh_gen pull request #19
Opened 2023-09-12 16:47 UTC by dimomatt

2023-09-13 21:58 UTC, mgduda requested changes
This generally seems fine, but I've just left a couple of comments for consideration.

2023-09-13 21:58 UTC, mgduda commented on include/Point.hpp
> +        this->lon = atan2(cartPoint.y, cartPoint.x) * 180.0 / M_PI;
Keeping these in radians may be best, as that's what we ultimately store in the MPAS mesh file, and radians are also more convenient for use with math functions.

2023-09-13 21:58 UTC, mgduda commented on src/AbstractMesh.cpp
> +                         preNormalized.z * preNormalized.z);
Although not critical, it may be worth considering whether some of these calculations can be simplified through the use of other math functions; in this case, for example, could we use `sqrt(dotProduct(preNormalized, preNormalized))`?

2023-09-14 02:36 UTC, dimomatt commented on src/AbstractMesh.cpp
> +                         preNormalized.z * preNormalized.z);
Great point, and done here and in the crossProduct function. Future update might just include a "normalize to one" function in the point3D struct, might end up being convenient.

2023-09-14 02:38 UTC, merged